# Generated by Django 5.2.1 on 2025-05-29 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=128)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom par défaut', max_length=128)),
                ('responsable', models.CharField(default='Responsable par défaut', max_length=128)),
                ('objectif', models.CharField(default='Objectif par défaut', max_length=128)),
                ('membres', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
            ],
        ),
    ]
