# Generated by Django 5.2.1 on 2025-05-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commentaire_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='app.idee'),
        ),
        migrations.AlterField(
            model_name='like',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.idee'),
        ),
    ]
