# Generated by Django 5.2.7 on 2025-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_commentaire_projet_alter_like_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('domaine', models.CharField(choices=[('Technologie', 'Technologie'), ('Finance', 'Finance'), ('Santé', 'Santé'), ('Éducation', 'Éducation'), ('Autre', 'Autre')], max_length=50, verbose_name="Domaine d'activité")),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('message', models.TextField(verbose_name='Message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partnership_images/', verbose_name='Logo ou image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
